name: Deploy public to Pages (Self-Hosted)

on:
  push:
    branches: [main]
  workflow_dispatch:

# 必须加这个！给 actions 写权限
permissions:
  contents: write   # 允许 push 到 gh-pages
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy public to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_PAT }}
          publish_dir: ./public